const Data =[
  {
    id: 1,
    tit:'White rice and stew',
    desc:'Choose your perfect meal combination with Jollof, Fried, or White Rice, served alongside your preferred stew and three pieces of meat. Round off your dish with Plantain, Beans, or enjoy the best of both.',
    pic: '../div/food4.jpg',
    add: '100',
  },
  {
    id: 2,
    tit:'White rice and stew',
    desc:'Choose your perfect meal combination with Jollof, Fried, or White Rice, served alongside your preferred stew and three pieces of meat. Round off your dish with Plantain, Beans, or enjoy the best of both.',
    pic:'../div/food5.jpg',
    add: '100',
  }, 
  {
    id: 3,
    tit:'White rice and stew',
    desc:'Choose your perfect meal combination with Jollof, Fried, or White Rice, served alongside your preferred stew and three pieces of meat. Round off your dish with Plantain, Beans, or enjoy the best of both.',
    pic:'../div/food3.jpg',
    add: '100',
  },
  {
    id: 4,
    tit:'White rice and stew',
    desc:'Choose your perfect meal combination with Jollof, Fried, or White Rice, served alongside your preferred stew and three pieces of meat. Round off your dish with Plantain, Beans, or enjoy the best of both.',
    pic:'../div/food3.jpg',
    add: '100',
  }, 
  {
    id: 5,
    tit:'White rice and stew',
    desc:'Choose your perfect meal combination with Jollof, Fried, or White Rice, served alongside your preferred stew and three pieces of meat. Round off your dish with Plantain, Beans, or enjoy the best of both.',
    pic:'../div/food3.jpg',
    add: '100',
  }, 
  {
    id: 6,
    tit:'White rice and stew',
    desc:'Choose your perfect meal combination with Jollof, Fried, or White Rice, served alongside your preferred stew and three pieces of meat. Round off your dish with Plantain, Beans, or enjoy the best of both.',
    pic:'../div/food3.jpg',
    add: '100',
  }, 
  {
    id: 7,
    tit:'White rice and stew',
    desc:'Choose your perfect meal combination with Jollof, Fried, or White Rice, served alongside your preferred stew and three pieces of meat. Round off your dish with Plantain, Beans, or enjoy the best of both.',
    pic:'../div/food3.jpg',
    add: '100',
  }, 
  {
    id: 8,
    tit:'White rice and stew',
    desc:'Choose your perfect meal combination with Jollof, Fried, or White Rice, served alongside your preferred stew and three pieces of meat. Round off your dish with Plantain, Beans, or enjoy the best of both.',
    pic:'../div/food3.jpg',
    add: '100',
  },
  {
    id: 9,
    tit:'White rice and stew',
    desc:'Choose your perfect meal combination with Jollof, Fried, or White Rice, served alongside your preferred stew and three pieces of meat. Round off your dish with Plantain, Beans, or enjoy the best of both.',
    pic:'../div/food4.jpg',
    add: '100',
  }, 
  {
    id: 10,
    tit:'White rice and stew',
    desc:'Choose your perfect meal combination with Jollof, Fried, or White Rice, served alongside your preferred stew and three pieces of meat. Round off your dish with Plantain, Beans, or enjoy the best of both.',
    pic:'../div/food1.jpg',
    add: '100',
  }, 
  {
    id: 11,
    tit:'White rice and stew',
    desc:'Choose your perfect meal combination with Jollof, Fried, or White Rice, served alongside your preferred stew and three pieces of meat. Round off your dish with Plantain, Beans, or enjoy the best of both.',
    pic:'../div/food3.jpg',
    add: '100',
  }, 
  {
    id: 12,
    tit:'White rice and stew',
    desc:'Choose your perfect meal combination with Jollof, Fried, or White Rice, served alongside your preferred stew and three pieces of meat. Round off your dish with Plantain, Beans, or enjoy the best of both.',
    pic:'../div/food3.jpg',
    add: '100',
  }, 
  {
    id: 13,
    tit:'White rice and stew',
    desc:'Choose your perfect meal combination with Jollof, Fried, or White Rice, served alongside your preferred stew and three pieces of meat. Round off your dish with Plantain, Beans, or enjoy the best of both.',
    pic:'../div/food3.jpg',
    add: '100',
  }, 
  {
    id: 14,
    tit:'White rice and stew',
    desc:'Choose your perfect meal combination with Jollof, Fried, or White Rice, served alongside your preferred stew and three pieces of meat. Round off your dish with Plantain, Beans, or enjoy the best of both.',
    pic:'../div/food16.jpg',
    add: '100',
  },
]

export default Data