const Map = [
  { id: 1,
    vid:'div/13.jpg',
    des: 'Football',
    cat: 'Comedy',
    tit: 'Onana saved a late minutes penalty as man united defeated Copenhengen by a lone goal scored by their former captain Harry Maguire. it is said to be a redemption night from Onana and Maguire.',
  },
  { id: 2,
    vid:'div/13.jpg',
    des: 'Football',
    cat: 'Foot',
    tit: 'Onana saved a late minutes penalty as man united defeated Copenhengen by a lone goal scored by their former captain Harry Maguire. it is said to be a redemption night from Onana and Maguire.',
  },
  { id: 3,
    vid:'div/9.jpg',
    des: 'Football',
    cat: 'Comedy',
    tit: 'Onana saved a late minutes penalty as man united defeated Copenhengen by a lone goal scored by their former captain Harry Maguire. it is said to be a redemption night from Onana and Maguire.',
  },
  { id: 4,
    vid:'div/7.jpg',
    des: 'Football',
    cat: 'Comedy',
    tit: 'Onana saved a late minutes penalty as man united defeated Copenhengen by a lone goal scored by their former captain Harry Maguire. it is said to be a redemption night from Onana and Maguire.',
  },
  { id: 5,
    vid:'div/4.jpg',
    des: 'Football',
    cat: 'Foot',
    tit: 'Onana saved a late minutes penalty as man united defeated Copenhengen by a lone goal scored by their former captain Harry Maguire. it is said to be a redemption night from Onana and Maguire.'
  },
  { id: 6,
    vid:'div/9.jpg',
    cat: 'Foot',
    tit: 'Onana saved a late minutes penalty as man united defeated Copenhengen by a lone goal scored by their former captain Harry Maguire. it is said to be a redemption night from Onana and Maguire.',
    des: 'Football',
  }
]

export default Map